language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=Django==1.4.2
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.7

# command to install dependencies
install:
  - pip install $DJANGO_VERSION
  - pip install -r test-requirements.txt

# command to run tests

script:
  - python runtests.py


matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.2